# Generated by Django 3.1.2 on 2022-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
